swagger: "2.0"
info:
  title: api/v1/trip.proto
  version: version not set
tags:
  - name: api
consumes:
  - application/json
produces:
  - application/json
paths:
  /trip/v1/generate:
    post:
      operationId: api_GenerateTrip
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GenerateTripResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GenerateTripRequest'
      tags:
        - api
  /trip/v1/get/{id}:
    get:
      operationId: api_GetTrip
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetTripResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - api
definitions:
  DayPlanEvent:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      place:
        $ref: '#/definitions/v1Place'
      startTime:
        type: string
        format: int64
      endTime:
        type: string
        format: int64
      image:
        type: string
  GetTripResponseTrip:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      description:
        type: string
        title: empty unless user changed
      startDate:
        type: string
        title: for DB query
      endDate:
        type: string
        title: for DB query
      currency:
        type: string
      plan:
        type: object
        additionalProperties:
          $ref: '#/definitions/TripDayPlan'
      breakdown:
        $ref: '#/definitions/TripBreakdown'
  TripBreakdown:
    type: object
    properties:
      totalActivityExpense:
        type: integer
        format: int32
      totalTransportExpense:
        type: integer
        format: int32
      totalLivingExpense:
        type: integer
        format: int32
      totalMealExpense:
        type: integer
        format: int32
  TripDayPlan:
    type: object
    properties:
      events:
        type: array
        items:
          type: object
          $ref: '#/definitions/DayPlanEvent'
      temperature:
        type: string
      activityExpense:
        type: integer
        format: int32
      transportExpense:
        type: integer
        format: int32
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1GenerateTripRequest:
    type: object
    properties:
      city:
        type: array
        items:
          type: string
      startDate:
        type: string
      endDate:
        type: string
      numOfPpl:
        type: integer
        format: int32
      theme:
        type: string
      interest:
        type: string
      budget:
        type: integer
        format: int32
  v1GenerateTripResponse:
    type: object
    properties:
      id:
        type: string
  v1GetTripResponse:
    type: object
    properties:
      trip:
        $ref: '#/definitions/GetTripResponseTrip'
  v1Place:
    type: object
    properties:
      placeId:
        type: integer
        format: int32
      name:
        type: string
      description:
        type: string
      category:
        type: string
      rating:
        type: number
        format: float
      address:
        type: string
      area:
        type: string
      url:
        type: string
      tel:
        type: string
      lat:
        type: number
        format: double
      lng:
        type: number
        format: double
      openingHours:
        type: array
        items:
          type: string
        title: 09:00am-18:30
      reservable:
        type: boolean
      priceLv:
        type: string
      price:
        type: array
        items:
          type: number
          format: float
      image:
        type: array
        items:
          type: string
